### ISSUE TITLE
How to get it to work with Karma test runner

### ISSUE THREAD

**Issue by Phatzor** [pitr/angular-rails-templates#63] opened 2014-08-03 18:38 UTC
Hi,

I am having issues getting the gem to work with the karma testrunner, because it can't find the 'templates' module.

Are there any way in how I can include the Javascript from the 'templates' module in my configuration for Karma?

Error message:
Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by dmarsupastar** [comment] 2015-01-13 17:57
I think that's right. So I believe the problem is with this file in the gem: vendor/assets/angular-rails-templates.js.erb. 

We see this file has one line which is 
```angular.module("<%= Rails.configuration.angular_templates.module_name %>", []);```

The embedded ruby does not get preprocessed when you require it for karma. 

You want to somehow run the embedded ruby preprocessor so that ```"<%= Rails.configuration.angular_templates.module_name %>"``` changes to "templates".

However. If you change this to 
```angular.module("templates", [])```
it will work, but it is only a temporary solution.

**Comment by kimardenmiller** [comment] 2015-01-13 18:26
@dmarsupastar, makes sense. E2E testing would be different, but unit testing will still need these templates.  Thanks!

**Comment by pitr** [comment] 2016-04-25 05:22
closing old task

**Closed by pitr** 2016-04-25 05:22 UTC

**Comment by jkruse14** [comment] 2017-07-08 21:45
Sorry for reviving and old issue, but I just wanted to note here that adding to the `development.rb` file:

`config.assets.prefix = "/dev-assets"`

will precompile your assets into a "dev' folder. You can then add to your karma config:

```
files: [
   ...
    './public/dev-assets/*.js'`,
    ...
];
```
